repos:
    - repo: https://github.com/gitguardian/ggshield
      rev: v1.12.0
      hooks:
          - id: ggshield
            language_version: python3
            stages: [commit]

    # -   repo: https://github.com/pre-commit/mirrors-jshint
    #     rev: ''  # Use the sha / tag you want to point at
    #     hooks:
    #     -   id: jshint

    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: 'v2.7.1' # Use the sha / tag you want to point at
      hooks:
          - id: prettier
            exclude: |
                (?x)^(
                    .github/.*|
                    src/config/.*|
                    src/CHANGELOG.md|
                    src/config/.*|
                    changelog.md
                )$

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0 # Use the ref you want to point at
      hooks:
          - id: check-case-conflict
          - id: check-json
            exclude: |
                (?x)^(
                    .vscode/launch.json
                )$
          - id: check-xml
          - id: check-yaml
          - id: detect-private-key
